package com.newthread.entity;

import java.io.Serializable;

public class Aboutourteam implements Serializable{
    private Integer aboutSid;

    private String aboutPicture;

    private String aboutQq;

    private String aboutWeibo;

    private String aboutTel;

    private String aboutMail;

    private String aboutMaster;

    private String aboutWechat;

    private String aboutFacebook;

    private String aboutTwitter;

    private Integer aboutTimesstamp;

    private String aboutIntroduce;

    private String aboutNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AboutOurTeam
     *
     * @mbggenerated
     */
    public Aboutourteam(Integer aboutSid, String aboutPicture, String aboutQq, String aboutWeibo, String aboutTel, String aboutMail, String aboutMaster, String aboutWechat, String aboutFacebook, String aboutTwitter, Integer aboutTimesstamp, String aboutIntroduce, String aboutNote) {
        this.aboutSid = aboutSid;
        this.aboutPicture = aboutPicture;
        this.aboutQq = aboutQq;
        this.aboutWeibo = aboutWeibo;
        this.aboutTel = aboutTel;
        this.aboutMail = aboutMail;
        this.aboutMaster = aboutMaster;
        this.aboutWechat = aboutWechat;
        this.aboutFacebook = aboutFacebook;
        this.aboutTwitter = aboutTwitter;
        this.aboutTimesstamp = aboutTimesstamp;
        this.aboutIntroduce = aboutIntroduce;
        this.aboutNote = aboutNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AboutOurTeam
     *
     * @mbggenerated
     */
    public Aboutourteam() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_sid
     *
     * @return the value of AboutOurTeam.about_sid
     *
     * @mbggenerated
     */
    public Integer getAboutSid() {
        return aboutSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_sid
     *
     * @param aboutSid the value for AboutOurTeam.about_sid
     *
     * @mbggenerated
     */
    public void setAboutSid(Integer aboutSid) {
        this.aboutSid = aboutSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_picture
     *
     * @return the value of AboutOurTeam.about_picture
     *
     * @mbggenerated
     */
    public String getAboutPicture() {
        return aboutPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_picture
     *
     * @param aboutPicture the value for AboutOurTeam.about_picture
     *
     * @mbggenerated
     */
    public void setAboutPicture(String aboutPicture) {
        this.aboutPicture = aboutPicture == null ? null : aboutPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_qq
     *
     * @return the value of AboutOurTeam.about_qq
     *
     * @mbggenerated
     */
    public String getAboutQq() {
        return aboutQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_qq
     *
     * @param aboutQq the value for AboutOurTeam.about_qq
     *
     * @mbggenerated
     */
    public void setAboutQq(String aboutQq) {
        this.aboutQq = aboutQq == null ? null : aboutQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_weibo
     *
     * @return the value of AboutOurTeam.about_weibo
     *
     * @mbggenerated
     */
    public String getAboutWeibo() {
        return aboutWeibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_weibo
     *
     * @param aboutWeibo the value for AboutOurTeam.about_weibo
     *
     * @mbggenerated
     */
    public void setAboutWeibo(String aboutWeibo) {
        this.aboutWeibo = aboutWeibo == null ? null : aboutWeibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_tel
     *
     * @return the value of AboutOurTeam.about_tel
     *
     * @mbggenerated
     */
    public String getAboutTel() {
        return aboutTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_tel
     *
     * @param aboutTel the value for AboutOurTeam.about_tel
     *
     * @mbggenerated
     */
    public void setAboutTel(String aboutTel) {
        this.aboutTel = aboutTel == null ? null : aboutTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_mail
     *
     * @return the value of AboutOurTeam.about_mail
     *
     * @mbggenerated
     */
    public String getAboutMail() {
        return aboutMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_mail
     *
     * @param aboutMail the value for AboutOurTeam.about_mail
     *
     * @mbggenerated
     */
    public void setAboutMail(String aboutMail) {
        this.aboutMail = aboutMail == null ? null : aboutMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_master
     *
     * @return the value of AboutOurTeam.about_master
     *
     * @mbggenerated
     */
    public String getAboutMaster() {
        return aboutMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_master
     *
     * @param aboutMaster the value for AboutOurTeam.about_master
     *
     * @mbggenerated
     */
    public void setAboutMaster(String aboutMaster) {
        this.aboutMaster = aboutMaster == null ? null : aboutMaster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_wechat
     *
     * @return the value of AboutOurTeam.about_wechat
     *
     * @mbggenerated
     */
    public String getAboutWechat() {
        return aboutWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_wechat
     *
     * @param aboutWechat the value for AboutOurTeam.about_wechat
     *
     * @mbggenerated
     */
    public void setAboutWechat(String aboutWechat) {
        this.aboutWechat = aboutWechat == null ? null : aboutWechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_facebook
     *
     * @return the value of AboutOurTeam.about_facebook
     *
     * @mbggenerated
     */
    public String getAboutFacebook() {
        return aboutFacebook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_facebook
     *
     * @param aboutFacebook the value for AboutOurTeam.about_facebook
     *
     * @mbggenerated
     */
    public void setAboutFacebook(String aboutFacebook) {
        this.aboutFacebook = aboutFacebook == null ? null : aboutFacebook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_twitter
     *
     * @return the value of AboutOurTeam.about_twitter
     *
     * @mbggenerated
     */
    public String getAboutTwitter() {
        return aboutTwitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_twitter
     *
     * @param aboutTwitter the value for AboutOurTeam.about_twitter
     *
     * @mbggenerated
     */
    public void setAboutTwitter(String aboutTwitter) {
        this.aboutTwitter = aboutTwitter == null ? null : aboutTwitter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_timesstamp
     *
     * @return the value of AboutOurTeam.about_timesstamp
     *
     * @mbggenerated
     */
    public Integer getAboutTimesstamp() {
        return aboutTimesstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_timesstamp
     *
     * @param aboutTimesstamp the value for AboutOurTeam.about_timesstamp
     *
     * @mbggenerated
     */
    public void setAboutTimesstamp(Integer aboutTimesstamp) {
        this.aboutTimesstamp = aboutTimesstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_introduce
     *
     * @return the value of AboutOurTeam.about_introduce
     *
     * @mbggenerated
     */
    public String getAboutIntroduce() {
        return aboutIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_introduce
     *
     * @param aboutIntroduce the value for AboutOurTeam.about_introduce
     *
     * @mbggenerated
     */
    public void setAboutIntroduce(String aboutIntroduce) {
        this.aboutIntroduce = aboutIntroduce == null ? null : aboutIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AboutOurTeam.about_note
     *
     * @return the value of AboutOurTeam.about_note
     *
     * @mbggenerated
     */
    public String getAboutNote() {
        return aboutNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AboutOurTeam.about_note
     *
     * @param aboutNote the value for AboutOurTeam.about_note
     *
     * @mbggenerated
     */
    public void setAboutNote(String aboutNote) {
        this.aboutNote = aboutNote == null ? null : aboutNote.trim();
    }

    @Override
    public String toString() {
        return "Aboutourteam{" +
                "aboutSid=" + aboutSid +
                ", aboutPicture='" + aboutPicture + '\'' +
                ", aboutQq='" + aboutQq + '\'' +
                ", aboutWeibo='" + aboutWeibo + '\'' +
                ", aboutTel='" + aboutTel + '\'' +
                ", aboutMail='" + aboutMail + '\'' +
                ", aboutMaster='" + aboutMaster + '\'' +
                ", aboutWechat='" + aboutWechat + '\'' +
                ", aboutFacebook='" + aboutFacebook + '\'' +
                ", aboutTwitter='" + aboutTwitter + '\'' +
                ", aboutTimesstamp=" + aboutTimesstamp +
                ", aboutIntroduce='" + aboutIntroduce + '\'' +
                ", aboutNote='" + aboutNote + '\'' +
                '}';
    }
}