package com.newthread.entity;

import java.util.Date;

public class File {
    private Integer fileSid;

    private Integer fileType;

    private String fileOriginName;

    private String fileName;

    private String filePath;

    private String fileUrl;

    private String fileComment;

    private Date fileUploadTime;

    private Long fileTimestamp;

    private String userAccount;

    private String fileNote;

    public File(Integer fileSid, Integer fileType, String fileOriginName, String fileName, String filePath, String fileUrl, String fileComment, Date fileUploadTime, Long fileTimestamp, String userAccount, String fileNote) {
        this.fileSid = fileSid;
        this.fileType = fileType;
        this.fileOriginName = fileOriginName;
        this.fileName = fileName;
        this.filePath = filePath;
        this.fileUrl = fileUrl;
        this.fileComment = fileComment;
        this.fileUploadTime = fileUploadTime;
        this.fileTimestamp = fileTimestamp;
        this.userAccount = userAccount;
        this.fileNote = fileNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated
     */
    public File() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_sid
     *
     * @return the value of file.file_sid
     *
     * @mbggenerated
     */
    public Integer getFileSid() {
        return fileSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_sid
     *
     * @param fileSid the value for file.file_sid
     *
     * @mbggenerated
     */
    public void setFileSid(Integer fileSid) {
        this.fileSid = fileSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_type
     *
     * @return the value of file.file_type
     *
     * @mbggenerated
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_type
     *
     * @param fileType the value for file.file_type
     *
     * @mbggenerated
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_origin_name
     *
     * @return the value of file.file_origin_name
     *
     * @mbggenerated
     */
    public String getFileOriginName() {
        return fileOriginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_origin_name
     *
     * @param fileOriginName the value for file.file_origin_name
     *
     * @mbggenerated
     */
    public void setFileOriginName(String fileOriginName) {
        this.fileOriginName = fileOriginName == null ? null : fileOriginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_name
     *
     * @return the value of file.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_name
     *
     * @param fileName the value for file.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_path
     *
     * @return the value of file.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_path
     *
     * @param filePath the value for file.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_url
     *
     * @return the value of file.file_url
     *
     * @mbggenerated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_url
     *
     * @param fileUrl the value for file.file_url
     *
     * @mbggenerated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_comment
     *
     * @return the value of file.file_comment
     *
     * @mbggenerated
     */
    public String getFileComment() {
        return fileComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_comment
     *
     * @param fileComment the value for file.file_comment
     *
     * @mbggenerated
     */
    public void setFileComment(String fileComment) {
        this.fileComment = fileComment == null ? null : fileComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_upload_time
     *
     * @return the value of file.file_upload_time
     *
     * @mbggenerated
     */
    public Date getFileUploadTime() {
        return fileUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_upload_time
     *
     * @param fileUploadTime the value for file.file_upload_time
     *
     * @mbggenerated
     */
    public void setFileUploadTime(Date fileUploadTime) {
        this.fileUploadTime = fileUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_timestamp
     *
     * @return the value of file.file_timestamp
     *
     * @mbggenerated
     */
    public Long getFileTimestamp() {
        return fileTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_timestamp
     *
     * @param fileTimestamp the value for file.file_timestamp
     *
     * @mbggenerated
     */
    public void setFileTimestamp(Long fileTimestamp) {
        this.fileTimestamp = fileTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.user_account
     *
     * @return the value of file.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.user_account
     *
     * @param userAccount the value for file.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_note
     *
     * @return the value of file.file_note
     *
     * @mbggenerated
     */
    public String getFileNote() {
        return fileNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_note
     *
     * @param fileNote the value for file.file_note
     *
     * @mbggenerated
     */
    public void setFileNote(String fileNote) {
        this.fileNote = fileNote == null ? null : fileNote.trim();
    }
}