package com.newthread.entity;

import java.util.Date;

public class Images {

    public static final int NEWS_TYPE = 1;

    public static final int PHOTOS_TYPE = 2;

    public static final String NEWS_PREFIX = "/news/";

    public static final String PHOTO_PREFIX = "/photos/";

    private Integer imgSid;

    private Integer imgType;

    private String imgOriginName;

    private String imgName;

    private String imgPath;

    private String imgComment;

    private Date imgUploadTime;

    private Long imgTimestamp;

    private String userAccount;

    private String imgNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated
     */
    public Images(Integer imgSid, Integer imgType, String imgOriginName, String imgName, String imgPath, String imgComment, Date imgUploadTime, Long imgTimestamp, String userAccount, String imgNote) {
        this.imgSid = imgSid;
        this.imgType = imgType;
        this.imgOriginName = imgOriginName;
        this.imgName = imgName;
        this.imgPath = imgPath;
        this.imgComment = imgComment;
        this.imgUploadTime = imgUploadTime;
        this.imgTimestamp = imgTimestamp;
        this.userAccount = userAccount;
        this.imgNote = imgNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated
     */
    public Images() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.img_sid
     *
     * @return the value of images.img_sid
     *
     * @mbggenerated
     */
    public Integer getImgSid() {
        return imgSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.img_sid
     *
     * @param imgSid the value for images.img_sid
     *
     * @mbggenerated
     */
    public void setImgSid(Integer imgSid) {
        this.imgSid = imgSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.img_type
     *
     * @return the value of images.img_type
     *
     * @mbggenerated
     */
    public Integer getImgType() {
        return imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.img_type
     *
     * @param imgType the value for images.img_type
     *
     * @mbggenerated
     */
    public void setImgType(Integer imgType) {
        this.imgType = imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.img_origin_name
     *
     * @return the value of images.img_origin_name
     *
     * @mbggenerated
     */
    public String getImgOriginName() {
        return imgOriginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.img_origin_name
     *
     * @param imgOriginName the value for images.img_origin_name
     *
     * @mbggenerated
     */
    public void setImgOriginName(String imgOriginName) {
        this.imgOriginName = imgOriginName == null ? null : imgOriginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.img_name
     *
     * @return the value of images.img_name
     *
     * @mbggenerated
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.img_name
     *
     * @param imgName the value for images.img_name
     *
     * @mbggenerated
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.img_path
     *
     * @return the value of images.img_path
     *
     * @mbggenerated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.img_path
     *
     * @param imgPath the value for images.img_path
     *
     * @mbggenerated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.img_comment
     *
     * @return the value of images.img_comment
     *
     * @mbggenerated
     */
    public String getImgComment() {
        return imgComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.img_comment
     *
     * @param imgComment the value for images.img_comment
     *
     * @mbggenerated
     */
    public void setImgComment(String imgComment) {
        this.imgComment = imgComment == null ? null : imgComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.img_upload_time
     *
     * @return the value of images.img_upload_time
     *
     * @mbggenerated
     */
    public Date getImgUploadTime() {
        return imgUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.img_upload_time
     *
     * @param imgUploadTime the value for images.img_upload_time
     *
     * @mbggenerated
     */
    public void setImgUploadTime(Date imgUploadTime) {
        this.imgUploadTime = imgUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.img_timestamp
     *
     * @return the value of images.img_timestamp
     *
     * @mbggenerated
     */
    public Long getImgTimestamp() {
        return imgTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.img_timestamp
     *
     * @param imgTimestamp the value for images.img_timestamp
     *
     * @mbggenerated
     */
    public void setImgTimestamp(Long imgTimestamp) {
        this.imgTimestamp = imgTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.user_account
     *
     * @return the value of images.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.user_account
     *
     * @param userAccount the value for images.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.img_note
     *
     * @return the value of images.img_note
     *
     * @mbggenerated
     */
    public String getImgNote() {
        return imgNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.img_note
     *
     * @param imgNote the value for images.img_note
     *
     * @mbggenerated
     */
    public void setImgNote(String imgNote) {
        this.imgNote = imgNote == null ? null : imgNote.trim();
    }
}