package com.newthread.entity;

import java.io.Serializable;

public class RolePower implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role_power.role_number
     *
     * @mbggenerated
     */
    private String roleNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role_power.power_number
     *
     * @mbggenerated
     */
    private String powerNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role_power
     *
     * @mbggenerated
     */
    public RolePower(String roleNumber, String powerNumber) {
        this.roleNumber = roleNumber;
        this.powerNumber = powerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role_power
     *
     * @mbggenerated
     */
    public RolePower() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role_power.role_number
     *
     * @return the value of Role_power.role_number
     *
     * @mbggenerated
     */
    public String getRoleNumber() {
        return roleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role_power.role_number
     *
     * @param roleNumber the value for Role_power.role_number
     *
     * @mbggenerated
     */
    public void setRoleNumber(String roleNumber) {
        this.roleNumber = roleNumber == null ? null : roleNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role_power.power_number
     *
     * @return the value of Role_power.power_number
     *
     * @mbggenerated
     */
    public String getPowerNumber() {
        return powerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role_power.power_number
     *
     * @param powerNumber the value for Role_power.power_number
     *
     * @mbggenerated
     */
    public void setPowerNumber(String powerNumber) {
        this.powerNumber = powerNumber == null ? null : powerNumber.trim();
    }
}