package com.newthread.entity;

import java.io.Serializable;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.role_number
     *
     * @mbggenerated
     */
    private String roleNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.role_sid
     *
     * @mbggenerated
     */
    private Integer roleSid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role
     *
     * @mbggenerated
     */
    public Role(String roleNumber, Integer roleSid, String roleName) {
        this.roleNumber = roleNumber;
        this.roleSid = roleSid;
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role
     *
     * @mbggenerated
     */
    public Role() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.role_number
     *
     * @return the value of Role.role_number
     *
     * @mbggenerated
     */
    public String getRoleNumber() {
        return roleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.role_number
     *
     * @param roleNumber the value for Role.role_number
     *
     * @mbggenerated
     */
    public void setRoleNumber(String roleNumber) {
        this.roleNumber = roleNumber == null ? null : roleNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.role_sid
     *
     * @return the value of Role.role_sid
     *
     * @mbggenerated
     */
    public Integer getRoleSid() {
        return roleSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.role_sid
     *
     * @param roleSid the value for Role.role_sid
     *
     * @mbggenerated
     */
    public void setRoleSid(Integer roleSid) {
        this.roleSid = roleSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.role_name
     *
     * @return the value of Role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.role_name
     *
     * @param roleName the value for Role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}