package com.newthread.entity;

import java.io.Serializable;

public class Teamdevelopment implements Serializable {
    private Integer develovpmentSid;

    private String developmentPicture;

    private Integer developmentTimesstamp;

    private String developmentContent;

    private String developmentNote;

    public Teamdevelopment(Integer develovpmentSid, String developmentPicture, Integer developmentTimesstamp, String developmentContent, String developmentNote) {
        this.develovpmentSid = develovpmentSid;
        this.developmentPicture = developmentPicture;
        this.developmentTimesstamp = developmentTimesstamp;
        this.developmentContent = developmentContent;
        this.developmentNote = developmentNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TeamDevelopment
     *
     * @mbggenerated
     */
    public Teamdevelopment() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamDevelopment.develovpment_sid
     *
     * @return the value of TeamDevelopment.develovpment_sid
     *
     * @mbggenerated
     */
    public Integer getDevelovpmentSid() {
        return develovpmentSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamDevelopment.develovpment_sid
     *
     * @param develovpmentSid the value for TeamDevelopment.develovpment_sid
     *
     * @mbggenerated
     */
    public void setDevelovpmentSid(Integer develovpmentSid) {
        this.develovpmentSid = develovpmentSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamDevelopment.development_picture
     *
     * @return the value of TeamDevelopment.development_picture
     *
     * @mbggenerated
     */
    public String getDevelopmentPicture() {
        return developmentPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamDevelopment.development_picture
     *
     * @param developmentPicture the value for TeamDevelopment.development_picture
     *
     * @mbggenerated
     */
    public void setDevelopmentPicture(String developmentPicture) {
        this.developmentPicture = developmentPicture == null ? null : developmentPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamDevelopment.development_timesstamp
     *
     * @return the value of TeamDevelopment.development_timesstamp
     *
     * @mbggenerated
     */
    public Integer getDevelopmentTimesstamp() {
        return developmentTimesstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamDevelopment.development_timesstamp
     *
     * @param developmentTimesstamp the value for TeamDevelopment.development_timesstamp
     *
     * @mbggenerated
     */
    public void setDevelopmentTimesstamp(Integer developmentTimesstamp) {
        this.developmentTimesstamp = developmentTimesstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamDevelopment.development_content
     *
     * @return the value of TeamDevelopment.development_content
     *
     * @mbggenerated
     */
    public String getDevelopmentContent() {
        return developmentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamDevelopment.development_content
     *
     * @param developmentContent the value for TeamDevelopment.development_content
     *
     * @mbggenerated
     */
    public void setDevelopmentContent(String developmentContent) {
        this.developmentContent = developmentContent == null ? null : developmentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamDevelopment.development_note
     *
     * @return the value of TeamDevelopment.development_note
     *
     * @mbggenerated
     */
    public String getDevelopmentNote() {
        return developmentNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamDevelopment.development_note
     *
     * @param developmentNote the value for TeamDevelopment.development_note
     *
     * @mbggenerated
     */
    public void setDevelopmentNote(String developmentNote) {
        this.developmentNote = developmentNote == null ? null : developmentNote.trim();
    }
}