package com.newthread.entity;

import java.util.Date;

public class Teammien {

    public static final int PHOTOS = 1;

    public static final int VIDEOS = 2;

    private Integer mienSid;

    private String mienTitle;

    private Integer mienType;

    private Date mienTime;

    private Integer mienTimesstamp;

    private String mienIntroduce;

    private String mienNote;

    public Teammien(Integer mienSid, String mienTitle, Integer mienType, Date mienTime, Integer mienTimesstamp, String mienIntroduce, String mienNote) {
        this.mienSid = mienSid;
        this.mienTitle = mienTitle;
        this.mienType = mienType;
        this.mienTime = mienTime;
        this.mienTimesstamp = mienTimesstamp;
        this.mienIntroduce = mienIntroduce;
        this.mienNote = mienNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammien
     *
     * @mbggenerated
     */
    public Teammien() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teammien.mien_sid
     *
     * @return the value of teammien.mien_sid
     * @mbggenerated
     */
    public Integer getMienSid() {
        return mienSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teammien.mien_sid
     *
     * @param mienSid the value for teammien.mien_sid
     * @mbggenerated
     */
    public void setMienSid(Integer mienSid) {
        this.mienSid = mienSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teammien.mien_title
     *
     * @return the value of teammien.mien_title
     * @mbggenerated
     */
    public String getMienTitle() {
        return mienTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teammien.mien_title
     *
     * @param mienTitle the value for teammien.mien_title
     * @mbggenerated
     */
    public void setMienTitle(String mienTitle) {
        this.mienTitle = mienTitle == null ? null : mienTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teammien.mien_type
     *
     * @return the value of teammien.mien_type
     * @mbggenerated
     */
    public Integer getMienType() {
        return mienType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teammien.mien_type
     *
     * @param mienType the value for teammien.mien_type
     * @mbggenerated
     */
    public void setMienType(Integer mienType) {
        this.mienType = mienType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teammien.mien_time
     *
     * @return the value of teammien.mien_time
     * @mbggenerated
     */
    public Date getMienTime() {
        return mienTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teammien.mien_time
     *
     * @param mienTime the value for teammien.mien_time
     * @mbggenerated
     */
    public void setMienTime(Date mienTime) {
        this.mienTime = mienTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teammien.mien_timesstamp
     *
     * @return the value of teammien.mien_timesstamp
     * @mbggenerated
     */
    public Integer getMienTimesstamp() {
        return mienTimesstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teammien.mien_timesstamp
     *
     * @param mienTimesstamp the value for teammien.mien_timesstamp
     * @mbggenerated
     */
    public void setMienTimesstamp(Integer mienTimesstamp) {
        this.mienTimesstamp = mienTimesstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teammien.mien_introduce
     *
     * @return the value of teammien.mien_introduce
     * @mbggenerated
     */
    public String getMienIntroduce() {
        return mienIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teammien.mien_introduce
     *
     * @param mienIntroduce the value for teammien.mien_introduce
     * @mbggenerated
     */
    public void setMienIntroduce(String mienIntroduce) {
        this.mienIntroduce = mienIntroduce == null ? null : mienIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teammien.mien_note
     *
     * @return the value of teammien.mien_note
     * @mbggenerated
     */
    public String getMienNote() {
        return mienNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teammien.mien_note
     *
     * @param mienNote the value for teammien.mien_note
     * @mbggenerated
     */
    public void setMienNote(String mienNote) {
        this.mienNote = mienNote == null ? null : mienNote.trim();
    }
}