package com.newthread.entity;

import java.io.Serializable;

/**
 * 团队组成成员
 */
public class Teammarkup implements Serializable {

    private Integer markupSid;

    private String markupName;

    private String markupPicture; //头像

    private String markupJob; //职位

    private String markupAcademy; //学院

    private String markupMajor; //专业

    private String markupGrade; //年级

    private String markupGroup; //组别

    private Integer markupTimestamp;

    private String markupContent; //座右铭之类的东西

    private String markupNote; //备注

    public Teammarkup(Integer markupSid, String markupPicture, String markupJob, String markupAcademy, String markupMajor, String markupGrade, String markupGroup, Integer markupTimestamp, String markupContent, String markupNote) {
        this.markupSid = markupSid;
        this.markupPicture = markupPicture;
        this.markupJob = markupJob;
        this.markupAcademy = markupAcademy;
        this.markupMajor = markupMajor;
        this.markupGrade = markupGrade;
        this.markupGroup = markupGroup;
        this.markupTimestamp = markupTimestamp;
        this.markupContent = markupContent;
        this.markupNote = markupNote;
    }

    public String getMarkupName() {
        return markupName;
    }

    public void setMarkupName(String markupName) {
        this.markupName = markupName;
    }

    public Teammarkup(Integer markupSid, String markupName, String markupPicture, String markupJob, String markupAcademy, String markupMajor, String markupGrade, String markupGroup, Integer markupTimestamp, String markupContent, String markupNote) {
        this.markupSid = markupSid;
        this.markupName = markupName;
        this.markupPicture = markupPicture;
        this.markupJob = markupJob;
        this.markupAcademy = markupAcademy;
        this.markupMajor = markupMajor;
        this.markupGrade = markupGrade;
        this.markupGroup = markupGroup;
        this.markupTimestamp = markupTimestamp;
        this.markupContent = markupContent;
        this.markupNote = markupNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TeamMarkUp
     *
     * @mbggenerated
     */
    public Teammarkup() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_sid
     *
     * @return the value of TeamMarkUp.markup_sid
     *
     * @mbggenerated
     */
    public Integer getMarkupSid() {
        return markupSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_sid
     *
     * @param markupSid the value for TeamMarkUp.markup_sid
     *
     * @mbggenerated
     */
    public void setMarkupSid(Integer markupSid) {
        this.markupSid = markupSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_picture
     *
     * @return the value of TeamMarkUp.markup_picture
     *
     * @mbggenerated
     */
    public String getMarkupPicture() {
        return markupPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_picture
     *
     * @param markupPicture the value for TeamMarkUp.markup_picture
     *
     * @mbggenerated
     */
    public void setMarkupPicture(String markupPicture) {
        this.markupPicture = markupPicture == null ? null : markupPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_job
     *
     * @return the value of TeamMarkUp.markup_job
     *
     * @mbggenerated
     */
    public String getMarkupJob() {
        return markupJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_job
     *
     * @param markupJob the value for TeamMarkUp.markup_job
     *
     * @mbggenerated
     */
    public void setMarkupJob(String markupJob) {
        this.markupJob = markupJob == null ? null : markupJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_academy
     *
     * @return the value of TeamMarkUp.markup_academy
     *
     * @mbggenerated
     */
    public String getMarkupAcademy() {
        return markupAcademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_academy
     *
     * @param markupAcademy the value for TeamMarkUp.markup_academy
     *
     * @mbggenerated
     */
    public void setMarkupAcademy(String markupAcademy) {
        this.markupAcademy = markupAcademy == null ? null : markupAcademy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_major
     *
     * @return the value of TeamMarkUp.markup_major
     *
     * @mbggenerated
     */
    public String getMarkupMajor() {
        return markupMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_major
     *
     * @param markupMajor the value for TeamMarkUp.markup_major
     *
     * @mbggenerated
     */
    public void setMarkupMajor(String markupMajor) {
        this.markupMajor = markupMajor == null ? null : markupMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_grade
     *
     * @return the value of TeamMarkUp.markup_grade
     *
     * @mbggenerated
     */
    public String getMarkupGrade() {
        return markupGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_grade
     *
     * @param markupGrade the value for TeamMarkUp.markup_grade
     *
     * @mbggenerated
     */
    public void setMarkupGrade(String markupGrade) {
        this.markupGrade = markupGrade == null ? null : markupGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_group
     *
     * @return the value of TeamMarkUp.markup_group
     *
     * @mbggenerated
     */
    public String getMarkupGroup() {
        return markupGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_group
     *
     * @param markupGroup the value for TeamMarkUp.markup_group
     *
     * @mbggenerated
     */
    public void setMarkupGroup(String markupGroup) {
        this.markupGroup = markupGroup == null ? null : markupGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_timestamp
     *
     * @return the value of TeamMarkUp.markup_timestamp
     *
     * @mbggenerated
     */
    public Integer getMarkupTimestamp() {
        return markupTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_timestamp
     *
     * @param markupTimestamp the value for TeamMarkUp.markup_timestamp
     *
     * @mbggenerated
     */
    public void setMarkupTimestamp(Integer markupTimestamp) {
        this.markupTimestamp = markupTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_content
     *
     * @return the value of TeamMarkUp.markup_content
     *
     * @mbggenerated
     */
    public String getMarkupContent() {
        return markupContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_content
     *
     * @param markupContent the value for TeamMarkUp.markup_content
     *
     * @mbggenerated
     */
    public void setMarkupContent(String markupContent) {
        this.markupContent = markupContent == null ? null : markupContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamMarkUp.markup_note
     *
     * @return the value of TeamMarkUp.markup_note
     *
     * @mbggenerated
     */
    public String getMarkupNote() {
        return markupNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamMarkUp.markup_note
     *
     * @param markupNote the value for TeamMarkUp.markup_note
     *
     * @mbggenerated
     */
    public void setMarkupNote(String markupNote) {
        this.markupNote = markupNote == null ? null : markupNote.trim();
    }
}