package com.newthread.entity;

import java.io.Serializable;
import java.util.Date;

public class Teamnews implements Serializable {

    private Integer newsSid;

    private String newsTitle;

    private String newsPicture;

    private String newsType;

    private String newsAuthor;

    private Integer newsReaders;

    private Date newsTime;

    private Integer newsTimesstamp;

    private String newsContend;

    private String newsNote;

    public Teamnews(Integer newsSid, String newsTitle, String newsPicture, String newsType, String newsAuthor, Integer newsReaders, Date newsTime, Integer newsTimesstamp, String newsContend, String newsNote) {
        this.newsSid = newsSid;
        this.newsTitle = newsTitle;
        this.newsPicture = newsPicture;
        this.newsType = newsType;
        this.newsAuthor = newsAuthor;
        this.newsReaders = newsReaders;
        this.newsTime = newsTime;
        this.newsTimesstamp = newsTimesstamp;
        this.newsContend = newsContend;
        this.newsNote = newsNote;
    }


    public String getNewsTitle() {
        return newsTitle;
    }

    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TeamNews
     *
     * @mbggenerated
     */
    public Teamnews() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamNews.news_sid
     *
     * @return the value of TeamNews.news_sid
     *
     * @mbggenerated
     */
    public Integer getNewsSid() {
        return newsSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamNews.news_sid
     *
     * @param newsSid the value for TeamNews.news_sid
     *
     * @mbggenerated
     */
    public void setNewsSid(Integer newsSid) {
        this.newsSid = newsSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamNews.news_picture
     *
     * @return the value of TeamNews.news_picture
     *
     * @mbggenerated
     */
    public String getNewsPicture() {
        return newsPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamNews.news_picture
     *
     * @param newsPicture the value for TeamNews.news_picture
     *
     * @mbggenerated
     */
    public void setNewsPicture(String newsPicture) {
        this.newsPicture = newsPicture == null ? null : newsPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamNews.news_type
     *
     * @return the value of TeamNews.news_type
     *
     * @mbggenerated
     */
    public String getNewsType() {
        return newsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamNews.news_type
     *
     * @param newsType the value for TeamNews.news_type
     *
     * @mbggenerated
     */
    public void setNewsType(String newsType) {
        this.newsType = newsType == null ? null : newsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamNews.news_author
     *
     * @return the value of TeamNews.news_author
     *
     * @mbggenerated
     */
    public String getNewsAuthor() {
        return newsAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamNews.news_author
     *
     * @param newsAuthor the value for TeamNews.news_author
     *
     * @mbggenerated
     */
    public void setNewsAuthor(String newsAuthor) {
        this.newsAuthor = newsAuthor == null ? null : newsAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamNews.news_readers
     *
     * @return the value of TeamNews.news_readers
     *
     * @mbggenerated
     */
    public Integer getNewsReaders() {
        return newsReaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamNews.news_readers
     *
     * @param newsReaders the value for TeamNews.news_readers
     *
     * @mbggenerated
     */
    public void setNewsReaders(Integer newsReaders) {
        this.newsReaders = newsReaders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamNews.news_time
     *
     * @return the value of TeamNews.news_time
     *
     * @mbggenerated
     */
    public Date getNewsTime() {
        return newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamNews.news_time
     *
     * @param newsTime the value for TeamNews.news_time
     *
     * @mbggenerated
     */
    public void setNewsTime(Date newsTime) {
        this.newsTime = newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamNews.news_timesstamp
     *
     * @return the value of TeamNews.news_timesstamp
     *
     * @mbggenerated
     */
    public Integer getNewsTimesstamp() {
        return newsTimesstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamNews.news_timesstamp
     *
     * @param newsTimesstamp the value for TeamNews.news_timesstamp
     *
     * @mbggenerated
     */
    public void setNewsTimesstamp(Integer newsTimesstamp) {
        this.newsTimesstamp = newsTimesstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamNews.news_contend
     *
     * @return the value of TeamNews.news_contend
     *
     * @mbggenerated
     */
    public String getNewsContend() {
        return newsContend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamNews.news_contend
     *
     * @param newsContend the value for TeamNews.news_contend
     *
     * @mbggenerated
     */
    public void setNewsContend(String newsContend) {
        this.newsContend = newsContend == null ? null : newsContend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TeamNews.news_note
     *
     * @return the value of TeamNews.news_note
     *
     * @mbggenerated
     */
    public String getNewsNote() {
        return newsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TeamNews.news_note
     *
     * @param newsNote the value for TeamNews.news_note
     *
     * @mbggenerated
     */
    public void setNewsNote(String newsNote) {
        this.newsNote = newsNote == null ? null : newsNote.trim();
    }

    @Override
    public String toString() {
        return "{" +
                "newsSid=" + newsSid +
                ", newsTitle='" + newsTitle + '\'' +
                ", newsPicture='" + newsPicture + '\'' +
                ", newsType='" + newsType + '\'' +
                ", newsAuthor='" + newsAuthor + '\'' +
                ", newsReaders=" + newsReaders +
                ", newsTime=" + newsTime +
                ", newsTimesstamp=" + newsTimesstamp +
                ", newsContend='" + newsContend + '\'' +
                ", newsNote='" + newsNote + '\'' +
                '}';
    }
}