package com.newthread.entity;

import java.io.Serializable;

public class User implements Serializable{

    private String userAccount;

    private Integer userSid;

    private String userName;

    private String password;

    public User(String userAccount, Integer userSid, String userName, String password) {
        this.userAccount = userAccount;
        this.userSid = userSid;
        this.userName = userName;
        this.password = password;
    }

    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.user_account
     *
     * @return the value of User.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.user_account
     *
     * @param userAccount the value for User.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.user_sid
     *
     * @return the value of User.user_sid
     *
     * @mbggenerated
     */
    public Integer getUserSid() {
        return userSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.user_sid
     *
     * @param userSid the value for User.user_sid
     *
     * @mbggenerated
     */
    public void setUserSid(Integer userSid) {
        this.userSid = userSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.user_name
     *
     * @return the value of User.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.user_name
     *
     * @param userName the value for User.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}