package com.newthread.entity;

import java.io.Serializable;

public class UserRole implements Serializable {

    private String userAccount;

    private String roleNumber;

    public UserRole(String userAccount, String roleNumber) {
        this.userAccount = userAccount;
        this.roleNumber = roleNumber;
    }

    public UserRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User_role.user_account
     *
     * @return the value of User_role.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User_role.user_account
     *
     * @param userAccount the value for User_role.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User_role.role_number
     *
     * @return the value of User_role.role_number
     *
     * @mbggenerated
     */
    public String getRoleNumber() {
        return roleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User_role.role_number
     *
     * @param roleNumber the value for User_role.role_number
     *
     * @mbggenerated
     */
    public void setRoleNumber(String roleNumber) {
        this.roleNumber = roleNumber == null ? null : roleNumber.trim();
    }
}