package com.newthread.entity;

import java.util.Date;

public class Videos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.v_sid
     *
     * @mbggenerated
     */
    private Integer vSid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.v_type
     *
     * @mbggenerated
     */
    private Integer vType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.v_origin_name
     *
     * @mbggenerated
     */
    private String vOriginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.v_name
     *
     * @mbggenerated
     */
    private String vName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.v_path
     *
     * @mbggenerated
     */
    private String vPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.v_comment
     *
     * @mbggenerated
     */
    private String vComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.v_upload_time
     *
     * @mbggenerated
     */
    private Date vUploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.v_timestamp
     *
     * @mbggenerated
     */
    private Long vTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.user_account
     *
     * @mbggenerated
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.v_note
     *
     * @mbggenerated
     */
    private String vNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated
     */
    public Videos(Integer vSid, Integer vType, String vOriginName, String vName, String vPath, String vComment, Date vUploadTime, Long vTimestamp, String userAccount, String vNote) {
        this.vSid = vSid;
        this.vType = vType;
        this.vOriginName = vOriginName;
        this.vName = vName;
        this.vPath = vPath;
        this.vComment = vComment;
        this.vUploadTime = vUploadTime;
        this.vTimestamp = vTimestamp;
        this.userAccount = userAccount;
        this.vNote = vNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated
     */
    public Videos() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.v_sid
     *
     * @return the value of videos.v_sid
     *
     * @mbggenerated
     */
    public Integer getvSid() {
        return vSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.v_sid
     *
     * @param vSid the value for videos.v_sid
     *
     * @mbggenerated
     */
    public void setvSid(Integer vSid) {
        this.vSid = vSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.v_type
     *
     * @return the value of videos.v_type
     *
     * @mbggenerated
     */
    public Integer getvType() {
        return vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.v_type
     *
     * @param vType the value for videos.v_type
     *
     * @mbggenerated
     */
    public void setvType(Integer vType) {
        this.vType = vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.v_origin_name
     *
     * @return the value of videos.v_origin_name
     *
     * @mbggenerated
     */
    public String getvOriginName() {
        return vOriginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.v_origin_name
     *
     * @param vOriginName the value for videos.v_origin_name
     *
     * @mbggenerated
     */
    public void setvOriginName(String vOriginName) {
        this.vOriginName = vOriginName == null ? null : vOriginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.v_name
     *
     * @return the value of videos.v_name
     *
     * @mbggenerated
     */
    public String getvName() {
        return vName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.v_name
     *
     * @param vName the value for videos.v_name
     *
     * @mbggenerated
     */
    public void setvName(String vName) {
        this.vName = vName == null ? null : vName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.v_path
     *
     * @return the value of videos.v_path
     *
     * @mbggenerated
     */
    public String getvPath() {
        return vPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.v_path
     *
     * @param vPath the value for videos.v_path
     *
     * @mbggenerated
     */
    public void setvPath(String vPath) {
        this.vPath = vPath == null ? null : vPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.v_comment
     *
     * @return the value of videos.v_comment
     *
     * @mbggenerated
     */
    public String getvComment() {
        return vComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.v_comment
     *
     * @param vComment the value for videos.v_comment
     *
     * @mbggenerated
     */
    public void setvComment(String vComment) {
        this.vComment = vComment == null ? null : vComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.v_upload_time
     *
     * @return the value of videos.v_upload_time
     *
     * @mbggenerated
     */
    public Date getvUploadTime() {
        return vUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.v_upload_time
     *
     * @param vUploadTime the value for videos.v_upload_time
     *
     * @mbggenerated
     */
    public void setvUploadTime(Date vUploadTime) {
        this.vUploadTime = vUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.v_timestamp
     *
     * @return the value of videos.v_timestamp
     *
     * @mbggenerated
     */
    public Long getvTimestamp() {
        return vTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.v_timestamp
     *
     * @param vTimestamp the value for videos.v_timestamp
     *
     * @mbggenerated
     */
    public void setvTimestamp(Long vTimestamp) {
        this.vTimestamp = vTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.user_account
     *
     * @return the value of videos.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.user_account
     *
     * @param userAccount the value for videos.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.v_note
     *
     * @return the value of videos.v_note
     *
     * @mbggenerated
     */
    public String getvNote() {
        return vNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.v_note
     *
     * @param vNote the value for videos.v_note
     *
     * @mbggenerated
     */
    public void setvNote(String vNote) {
        this.vNote = vNote == null ? null : vNote.trim();
    }
}