package com.newthread.framework.mapper;

import com.newthread.entity.Images;
import com.newthread.model.MienImageModel;

import java.util.List;

public interface ImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer imgSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated
     */
    int insert(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated
     */
    Images selectByPrimaryKey(Integer imgSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated
     */
    List<Images> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Images record);

    List<MienImageModel> selectByPhotoSid(String sid);
}