package com.newthread.framework.mapper;

import com.newthread.entity.Power;
import java.util.List;

public interface PowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Power
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String powerNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Power
     *
     * @mbggenerated
     */
    int insert(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Power
     *
     * @mbggenerated
     */
    Power selectByPrimaryKey(String powerNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Power
     *
     * @mbggenerated
     */
    List<Power> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Power
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Power record);
}