package com.newthread.framework.mapper;

import com.newthread.entity.Role;
import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role
     *
     * @mbggenerated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role
     *
     * @mbggenerated
     */
    Role selectByPrimaryKey(String roleNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role
     *
     * @mbggenerated
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Role record);

    String selectAdmin();

    /**
     * 大于0 就存在
     * @param role
     * @return
     */
    Integer existByRoleNumber(String role);
}