package com.newthread.framework.mapper;

import com.newthread.entity.Teamnews;
import com.newthread.model.NewsModelWithImages;

import java.util.Date;
import java.util.List;

public interface TeamnewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TeamNews
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer newsSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TeamNews
     *
     * @mbggenerated
     */
    int insert(Teamnews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TeamNews
     *
     * @mbggenerated
     */
    Teamnews selectByPrimaryKey(Integer newsSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TeamNews
     *
     * @mbggenerated
     */
    List<Teamnews> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TeamNews
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Teamnews record);

    List<Teamnews> select(int i, Integer s);

    int getRecord();

    Teamnews selectOneNewestNews();

    /**
     * 倒序选出一篇新闻 , 逻辑: 最后一篇,倒数第一篇,倒数第三篇
     *
     * @param i 第几条
     * @return
     */
    Teamnews getNewsByDescOrderNumber(int i);

    Integer deleteNewBySid(Integer id);

    Integer updateNew(Integer newsSid, String newsTitle, String newsPicture, String newsType,
                      String newsAuthor, Integer newsReaders, Date newsTime, Integer newsTimesstamp,
                      String newsContend, String newsNote);

    Integer addNew(String newsTitle, String newsPicture, String newsType,
                   String newsAuthor, Integer newsReaders, Date newsTime, Integer newsTimesstamp,
                   String newsContend, String newsNote);

    NewsModelWithImages selectByPrimaryKeyWithImages(Integer id);
}