package com.newthread.framework.mapper;

import com.newthread.entity.Teammien;
import com.newthread.model.MienModel;

import java.util.List;

public interface TeammienMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammien
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mienSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teammien
     *
     * @mbggenerated
     */
    int insert(Teammien record);

    Teammien selectByPrimaryKey(Integer mienSid);

    List<Teammien> selectAll();

    int updateByPrimaryKey(Teammien record);

    List<Teammien> selectByType(int type);

    List<MienModel> selectByTypeModel(int photos);
}