package com.newthread.framework.mapper;

import com.newthread.entity.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String userAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    List<String> getAllPermission(Object principal);

    User getOneAdmin();

    Integer checkPassword(String account, String passwd);

    int add(User user);

    Integer exist(String account);

    Integer deleteUserRole(String account);

    int updatePassword(String account, String newpw);

    int updateInfo(User user);
}