package com.newthread.framework.mapper;

import com.newthread.entity.Videos;

import java.util.List;

public interface VideosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated
     */
    int insert(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated
     */
    Videos selectByPrimaryKey(Integer vSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated
     */
    List<Videos> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Videos record);
}